apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: develop
  labels:
    app: schema-registry-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry-app
  template:
    metadata:
      labels:
        app: schema-registry-app
    spec:
      containers:
        - name: schema-registry-container
          image: confluentinc/cp-schema-registry:latest
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: 'schema-registry-svc'
            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
              value: 'zookeeper-svc.develop.svc.cluster.local:2181'
            - name: SCHEMA_REGISTRY_LISTENERS
              value: 'http://0.0.0.0:8081'
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: 'PLAINTEXT://kafka-svc.develop.svc.cluster.local:9093'
            - name: SCHEMA_REGISTRY_DEBUG
              value: 'true'
