apiVersion: v1
kind: Service
metadata:
  name: schema-registry-svc
  namespace: mage-dev
  labels:
    app: schema-registry-app
spec:
  ports:
    - name: '8081'
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: schema-registry-app
