apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-applicationset-controller
rules:
  # Existing rules for admissionregistration.k8s.io API
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "validatingadmissionpolicies"
      - "validatingadmissionpolicybindings"
      - "mutatingwebhookconfigurations"
      - "validatingwebhookconfigurations"
    verbs:
      - get
      - list
      - watch
      - "create"
      - "update"
      - "patch"
      - "delete"

  # New rule for PodTemplate in the core API group
  - apiGroups:
      - ""  # Core API group (no API group)
    resources:
      - "podtemplates"
    verbs:
      - get
      - list
      - watch

  # Additional resources Argo CD might need access to:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "services"
      - "configmaps"
      - "secrets"
      - "persistentvolumeclaims"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "statefulsets"
      - "daemonsets"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - "batch"
    resources:
      - "jobs"
      - "cronjobs"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Add permissions for LimitRange
  - apiGroups:
      - ""  # Core API group
    resources:
      - "limitranges"
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["argoproj.io"]
    resources: ["applications", "applicationsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["argoproj.io"]
    resources: ["appprojects"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""  # Core API group
    resources:
      - replicationcontrollers
    verbs:
      - get
      - list
      - watch
  
  - apiGroups:
      - "scheduling.k8s.io"  # API group for scheduling-related resources
    resources:
      - priorityclasses
    verbs:
      - get
      - list
      - watch
  
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - "storage.k8s.io"  # API group for storage-related resources
    resources:
      - csinodes
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - "storage.k8s.io"  # API group for storage-related resources
    resources:
      - csistoragecapacities  # Add csistoragecapacities
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apiregistration.k8s.io"
    resources:
      - "apiservices"
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["flowcontrol.apiserver.k8s.io"]
    resources: ["prioritylevelconfigurations"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["list", "get", "watch"]