apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller
rules:
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "validatingadmissionpolicies"
      - "validatingadmissionpolicybindings"
    verbs:
      - get
      - list
      - watch
