apiVersion: v1
kind: Service
metadata:
  name: mageai
  namespace: develop
  labels:
    app: mageai
spec:
  type: ClusterIP
  ports:
    - port: 6789
      targetPort: 6789
      protocol: TCP
      name: http
  selector:
    app: mageai
