apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: develop
  labels:
    app: zookeeper-app
spec:
  serviceName: zookeeper-svc
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-app
  template:
    metadata:
      labels:
        app: zookeeper-app
    spec:
      containers:
        - name: zookeeper-container
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '2181'
            - name: ZOOKEEPER_TICK_TIME
              value: '2000'
          volumeMounts:
            - name: data
              mountPath: /mnt/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"