name: Argo CD Deploy Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'  # Only triggers if files under `apps/` change

jobs:
  validate-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Identify Changed Application Directories
        id: changes
        run: |
          CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | grep '^apps/' | cut -d'/' -f1-2 | sort -u)
          echo "changed_dirs=$CHANGED_DIRS" >> $GITHUB_ENV
        shell: bash

      - name: Lint and Validate Manifests
        if: env.changed_dirs != ""
        run: |
          for dir in $CHANGED_DIRS; do
            if [ -f "$dir/kustomization.yaml" ]; then
              echo "Validating $dir"
              kubectl kustomize $dir | kubeval
            fi
          done

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Argo CD Login
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}

      - name: Sync Only Changed Argo CD Applications
        if: env.changed_dirs != ""
        run: |
          for dir in $CHANGED_DIRS; do
            app_name=$(basename $dir)  # Assuming each subdirectory corresponds to an Argo CD app name
            echo "Syncing application $app_name"
            argocd app sync $app_name
          done
