# kafka-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/georgezefko/kubernetes-roadmap.git'
    targetRevision: HEAD  # Use the branch or commit you want ArgoCD to track
    path: apps/kafka/dev       # Path to the dev folder in the Kafka component
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: develop   # Namespace where Kafka will be deployed
  syncPolicy:
    automated:
      prune: true        # Optionally, ArgoCD can prune resources that are not in Git
      selfHeal: true     # Optionally, ArgoCD can auto-heal resources that drift
