apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mage-ai
  namespace: argocd  # Namespace where Argo CD is installed, usually `argocd`
spec:
  project: default

  source:
    repoURL: https://mage-ai.github.io/helm-charts  # Direct link to Mage AI Helm repo
    chart: mageai
    targetRevision: 0.2.6  # Specify a version if needed
    path: apps/mage-ai/dev/
    helm:
      valueFiles:
        - values.yaml  # Path to your dev-specific values file, if using overlays

  destination:
    server: https://kubernetes.default.svc  # This points to the in-cluster Kubernetes API
    namespace: mage-ai  # The namespace where you want Mage AI deployed

  syncPolicy:
    automated:
      prune: true  # Automatically remove resources no longer in the chart
      selfHeal: true  # Automatically apply changes in the chart
