# schema-registry-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schema-registry-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/georgezefko/kubernetes-roadmap.git'
    targetRevision: HEAD
    path: schema-registry/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mage-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
