# zookeeper-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper-app
  namespace: argocd-dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/georgezefko/kubernetes-roadmap.git'
    targetRevision: main
    path: zookeeper/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mage-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
